### ISSUE TITLE
The toolbar disappear using https.

### ISSUE THREAD

**Issue by LowesDeveloper** [Wibiya/cdn#2]
Hi,

The toolbar disappear using https.

https://cdn.wibiya.com/Toolbars/   .js  "

Please help.

**Comment by dbashyal** [comment]
Hi LowesDeveloper,

I have free SSL so it gives warning when visiting site using https. For dedicated SSL it costs US$75-80/yr. So it's bit expensive to afford for me at the moment.

If you need https and have SSL installed on your site. You can host JS yourself to load toolbar properly.

Get latest JS code here - [http://www.tealdit.com/toolbar/v1.js](http://www.tealdit.com/toolbar/v1.js)

Regards,
dbashyal

**Comment by LowesDeveloper** [comment]
Thank you. I will download it.
